package_name: custom
version: 0.10.0dev
license: GPLv2+
authors: [Bohuslav Kabrda <bkabrda@redhat.com>]
homepage: https://github.com/devassistant/dap-custom
summary: Custom prep assistants to develop on an upstream project
bugreports: https://github.com/devassistant/dap-custom/issues
dependencies:
  - common_args
  - github
description: |
    The custom assistant sets up environment for developing custom project
    previously created with DevAssistant.

    If the project contains a .devassistant file, you may choose to execute it.
    However, only do so with projects you trust, since the file can contain
    arbitrary custom commands that will run on your machine.
